/*
 * This source file was generated by the Gradle 'init' task
 */
package jp.ac.uryukyu.ie.e245736;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //Frame frame = new Frame("オセロゲーム");
        Logic logic = new Logic();
        logic.printBoard();
    }
}
